### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jaszberenyisz**
I have added one more dependency, and I have modified the cron file creation and content section for a more professional way. I hope you don't mind it and please add it to the project :)

### CODE REVIEW

**Review by filipnet — COMMENTED** [review]
Thanks for the contribution, however, I would differentiate between Redhat and Debian-based distributions after the merge.

**Comment by jaszberenyisz** [comment]
Thank you very much! I am glad that you could merge it into the project :)

You have taken out the perl installation instructions. Maybe it would be nice to readd them. You find it in the documentation that i have sent. Maybe you should do the same as with the libxml installation. Have a separate Redhat and Debian command for the not so professional users is nice I think. :)

**Comment by filipnet** [comment]
Thank you, I did not remove the instructions for installing the Perl interpreter but consolidated them together with the libxml2-utils you added: ```apt install perl libxml2-utils```

**Comment by jaszberenyisz** [comment]
Sorry! :) I did not notice that detail.

**Pull request merged**
